### ISSUE TITLE
Bug: Error Unknown switches "--help"

### ISSUE THREAD

**Issue by luizpicolo** [fnando/dopstick#1]
## Description

Error accessing helper

## How to reproduce

When accessing the **--help** parameter the error is returned 

## What do you expect

Parameter list

## What happened instead

Unknown switches "--help"]

## Software:

- Gem version: 0.0.2
- Ruby version:  2.6.5

**Comment by fnando** [comment]
This is actually something that [Thor](http://whatisthor.com) doesn't support out of the box. You can issue `--help` on tail (e.g. `dopstick --help`), but have to use `dopstick help command` to show help for a given command.

I'll see what I can do.
